// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLBxXgOvgjOU2BwkP-2xpvUfXHus5Tdo',
    appId: '1:680584139861:web:9bfc196f624c1da48c30dc',
    messagingSenderId: '680584139861',
    projectId: 'test-cicd-finwise',
    authDomain: 'test-cicd-finwise.firebaseapp.com',
    storageBucket: 'test-cicd-finwise.firebasestorage.app',
    measurementId: 'G-BFBRP00Y44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3Ad0s647QH_0-D-wSm38azgdmci897A',
    appId: '1:680584139861:android:2e257d2d2187a5438c30dc',

    messagingSenderId: '680584139861',
    projectId: 'test-cicd-finwise',
    storageBucket: 'test-cicd-finwise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAYdop4S9PGjpPXoY-lQAog-cXN28zP8',
    appId: '1:680584139861:ios:9631ccd490517a348c30dc',
    messagingSenderId: '680584139861',
    projectId: 'test-cicd-finwise',
    storageBucket: 'test-cicd-finwise.firebasestorage.app',
    iosBundleId: 'com.example.financeWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvAYdop4S9PGjpPXoY-lQAog-cXN28zP8',
    appId: '1:680584139861:ios:9631ccd490517a348c30dc',
    messagingSenderId: '680584139861',
    projectId: 'test-cicd-finwise',
    storageBucket: 'test-cicd-finwise.firebasestorage.app',
    iosBundleId: 'com.example.financeWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNLBxXgOvgjOU2BwkP-2xpvUfXHus5Tdo',
    appId: '1:680584139861:web:1ff2933e888e4d168c30dc',
    messagingSenderId: '680584139861',
    projectId: 'test-cicd-finwise',
    authDomain: 'test-cicd-finwise.firebaseapp.com',
    storageBucket: 'test-cicd-finwise.firebasestorage.app',
    measurementId: 'G-HCVQEQ7MF1',
  );
}
